"""Alert model generated by detection engine."""
import uuid
from datetime import datetime
from sqlalchemy import Column, String, DateTime, Boolean, Text, ForeignKey, Integer
from sqlalchemy.dialects.postgresql import UUID, JSONB, ARRAY
from app.database import Base


class Alert(Base):
    __tablename__ = "alerts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title = Column(String(500), nullable=False)
    description = Column(Text, nullable=True)
    severity = Column(String(20), nullable=False, index=True)  # low, medium, high, critical
    status = Column(String(20), default="open", index=True)  # open, investigating, resolved, false_positive
    source = Column(String(100), nullable=True)  # detection rule name
    rule_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    source_ip = Column(String(45), nullable=True)
    dest_ip = Column(String(45), nullable=True)
    event_count = Column(Integer, default=1)
    mitre_tactic = Column(String(100), nullable=True)
    mitre_technique = Column(String(100), nullable=True)
    mitre_technique_id = Column(String(20), nullable=True)
    ioc_indicators = Column(JSONB, nullable=True)  # IOC extraction
    related_event_ids = Column(JSONB, nullable=True)  # list of event UUIDs
    incident_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    assigned_to = Column(UUID(as_uuid=True), nullable=True)
    is_false_positive = Column(Boolean, default=False)
    false_positive_reason = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    resolved_at = Column(DateTime, nullable=True)
    extra_data = Column(JSONB, nullable=True)
